quarkus.datasource.jdbc.url=jdbc:sqlserver://localhost:1434;databaseName=CentroServiciosDB;encrypt=true;trustServerCertificate=true
quarkus.datasource.username=sa
quarkus.datasource.password=Panda1997
quarkus.hibernate-orm.database.generation=none