quarkus.datasource.jdbc.url=jdbc:sqlserver://localhost:1434;databaseName=CentroServiciosDB;encrypt=true;trustServerCertificate=true
quarkus.datasource.username=sa
quarkus.datasource.password=Panda1997
quarkus.hibernate-orm.database.generation=none

# --------------- CONFIGURACIÓN FLYWAY --------------------
# Activar la migración automática al iniciar la app
quarkus.flyway.migrate-at-start=true
quarkus.flyway.schemas=centroservicios
quarkus.flyway.create-schemas=true
quarkus.hibernate-orm.database.default-schema=centroservicios